### PR TITLE
Refresh Recipe, Update to v6.0.1

### PR DESCRIPTION
**Pull request by rxm7706**
poetry-core required for build
Update Mando pin
Added Maintainer - Please feel free to remove me, If you do not need assistance.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@igortg @tonybaloney
Could you please review and merge.
PR description has all changes
Thank you and Regards.

**Review by tonybaloney — CHANGES_REQUESTED** [review]
PR looks good. Please remove the additional maintainer change and submit in a separate PR.

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
> PR looks good. Please remove the additional maintainer change and submit in a separate PR.

@tonybaloney - Removed myself as a co-maintainer, I don't need to be added, if you don't need additional help. Feel free to LMK if you need assistance. 
Thank you and Regards.

**Review by tonybaloney — APPROVED** [review]

**Pull request merged**
